### ISSUE TITLE
wp-jalali is not working on PHP 8.0

### ISSUE THREAD

**Issue by AmirMehrabi** [wp-persian/wp-jalali#50]
#### Description
When I tried to activate wp-jalali on a wordpress running on PHP 8.0, I encountered a bunch of issues related to syntax change in PHP.

#### Screenshots
Here's some of those issues that need fixing:
![Selection_724](https://user-images.githubusercontent.com/3878847/110979722-3a29d180-837a-11eb-909a-ecab43498781.png)
![Selection_723](https://user-images.githubusercontent.com/3878847/110979736-3dbd5880-837a-11eb-8f8a-5d38cb4f2e4e.png)

#### To Reproduce
1) Install wp-jalali on a wordpress running on PHP 8.0
2) Navigate to "Plugins", and Activate wp-jalali

#### Tasks 
- [x] List all of the code blocks that needs fixing
- [x] Update date.php with the new syntax changes
- [x] Activate and test the plugin

**Comment by AmirMehrabi** [comment]
I'm more than happy to help on this issue if it's alright with you guys.
